### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by KingAkrej** [foo290/Django-Verify-Email#7]
Whenever a user makes a registartion I get an email that the token is invalid. However, when the user is already registered and decides to change thier email address there are no issues with that. It used to function with no issues at all and I can't find out the cause of this problem.

**Comment by foo290** [comment]
1. you can't get an email saying **token is invalid,** if the **link** is invalid, it will show you an error webpage. 
2. This seems like an issue with the programming rather than package, I mean the package sends a link on provided email with the link and if the link is used for the first time, its valid otherwise invalid. This link validation (means the link will work only once) is done by changing the last_login stamp on user, so you change it somewhere else before verification, the link will be expired.

**Comment by foo290** [comment]
[here is how token is created](https://stackoverflow.com/questions/46234627/how-does-default-token-generator-store-tokens#:~:text=The%20first%20three%20values%20are,in%20or%20changes%20their%20password.)

**Comment by KingAkrej** [comment]
thank you for the warning was due to last_login
